boxwise/boxwise

firestore.rules
src/components/AppDrawer.js
src/components/AppDrawerAuth.js
src/components/AppDrawerAuthContainer.js
src/reducers/organisations.js

This wraps the auth widget in a container which takes responsibility for fetching organisation data and passing it down to the (boring, stateless) presentation component.
It's a bit dumb, as it just loads anything/everything in the `organisations` collection at the moment, but it mostly works and shouldn't fail if an `organisations` collection doesn't exist or the `organisations` property is missing from a user profile.
I've taken the liberty of simplifying the global `state.organisation` from an object to a string (or `null`), as I am assuming this was intended to track the "current" organisation for the view? But perhaps you intended something else? Anyway, very happy to make any necessary changes to this.

Load and display organisation data

---

src/components/AddBoxDialogContainer.js
src/components/AddProductDialogContainer.js
src/components/BoxList.js
src/components/BoxListContainer.js
src/components/ConfirmDeleteAlert.js
src/components/ProductTable.js
src/components/ProductTableContainer.js

Continuing @HaGuesto's work.
A few design decisions:
- Added a confirmation dialog, because deleting stuff accidentally is reeaally annoying
- Uses an isDeleted flag. All products in the database will now be considered deleted. But that's okay because there aren't any in the production database yet.
- When a product is deleted, it will still be referenced by the box but just display as "[none]" in the list. I think this is a pretty good interim solution to #109.
Looks a bit like this:
Closes #75
Closes #109

Support deleting products

---

src/App.js
src/components/ScrollToTop.js

This doesn't handle scrolling to correct position on
back/forward. react-router-scroll does this but doesn't
support react-router v4.
Fixes #95

Scroll to top on navigation

---

src/pages/CreateLabelsPage.css
src/pages/CreateLabelsPage.js

#136 
I provided the simplest possible solution: an explanation of this screen with a link back to the dashboard.

Provide a back option in the QR labels screen

---

src/actions/auth.js
src/actions/profile.js

If a UI update throws an error, the error will never be logged.
See #170

Log errors before dispatching error actions

---

.travis.yml

Test first without copying so we don't accidentally run tests
in production environment.

Copy production configuration before building

---

src/App.js
src/actions/auth.js
src/components/AppDrawerAuth.js
src/components/PasswordChangeForm.js
src/containers/components/PasswordChangeForm.js
src/containers/pages/PasswordChangeForm.js
src/pages/PasswordChangePage.js
src/reducers/user.js

Some key things I added:
1. added basic password validation and client-side error reporting on validation failure
2. do a sign in operation with user's existing email first, then immediately update user's password (firebase requires user to be recently signed in)
3. display success or failure message at the top of the password change page after user submit the request

#23 Added a new page to change user password, and linked it in snackbar

---

package.json
utils/generate-test-data.js

This should hopefully address issue #24
The new generate-test-data.js script will create a new organization with a single user profile, and add 10 randomly generated products and 5 randomly generated boxes to it.
It can be run with `yarn add-test-data` which will prompt the user for the email to use, a password, and the name of the organization to create. After that it will create the data in firestore, and they can log in with the newly created email/password and test things out in the app.

Script to set up a bunch of test data in development

---

src/components/ButtonWithProgress.js

The stacking boxes don't really work on buttons. Too small.

Use CircularProgress on buttons

---

src/components/SignInForm.test.js

- Import change - the component name is not the default export, thus the brackets import will fail
- Moved the setup out of it into before block
- passed userSignIn method to component
- Changed the order in which we do expect to simplify the test - doesn't need to be async as everything is mocked
- fixed jest argument matching to match returned value
- un-skip the test

#60 - Fixed component unit test for SignInForm

---

package.json
yarn.lock

The existing version is no longer supported and so you were unable to run 'yarn deploy-firestore'

Upgrading the firestore CLI tools

---

README.md

The workflow in the Google Cloud console for Firestore has changed a little, so updating the instructions.
I also had to update the firebase tooling versions to run the 'yarn run deploy-firestore' command, but I'll submit that separately.

Firestore UI has changed, updating docs to reflect

---

.travis.yml

Current deploys are failing due to an invalid API key. Not entirely sure why, but re-generating as it's been almost 12 months since the last deploy.
I've re-generated the key following the instructions here: https://docs.travis-ci.com/user/deployment/firebase/

Updated encrypted deploy key for Firebase

---

.travis.yml

This should allow us to turn off non-named branch builds in Travis and therefore only have one CI job per pull request

Add explicit reference to master branch in Travis config

---

package.json
yarn.lock

Unfortunately it seems react-app-rewired specifically requires v23.6 of jest, so will have to resolve this issue later

Bump react-app-rewired and peer dependency react-scripts to latest versions

---

src/firebase.js
utils/generate-test-data.js

timestampsInSnapshots always defaults to true and will be soon removed.

Fix to remove firebase deprecation warning

---

.travis.yml

Hopefully this gives us a new travis CI image and therefore a newer version of yarn. Current builds on travis are running on v1.3.2.

Bump Node version 

---

src/firebase.js
yarn.lock

**change**: firestore is initialized with offline persistance
**change**: yarn.lock changed after bumping react-firestore (maybe this is done already in some of the open dependabot-bot PRs?)

Enable firestore offline persistance

---

src/firebaseFactory.js
src/index.js
src/modules/auth/actions.js
src/modules/boxes/actions.js
src/modules/boxes/containers/BoxListContainer.js
src/modules/products/actions.js
src/modules/products/components/ProductsCollection.js
src/modules/profile/actions.js
src/modules/signup/actions.js
src/modules/signup/actions.test.js
src/setupTests.js

I broke this in https://github.com/boxwise/boxwise/commit/c91b894c78ca0ee3be92fff6897ea58a0d81f575 .  We need to pass around the specific configured instance - and firestore has to be explicitly included for the function to be available. This didn't fail any tests :/ I'm not addressing that here though, as we don't yet have a nice way to run integration tests across the app.

Fix up the firebase factory 

---

package.json
src/firestore.rules.test.js

Reverting change in https://github.com/boxwise/boxwise/commit/f7b7dddfc64ebfa3257be2d6f82839f99ebdadea as file detection didn't work. Fixing the import path instead.
Also, remove usage of NODE_PATH for testing as we're specifying via modulePaths anyway.

Fixing integration firestore tests

---

src/errorHandling.js
src/modules/auth/actions.js
src/modules/boxes/actions.js
src/modules/products/actions.js
src/modules/profile/actions.js
src/store.js

Hook up middleware to pick up our 'error' actions and throw them - which means they'll then be captured by Sentry and logged. This removes the need to call out to sentry within our actions directly.

Simplify action handlers error handling

---

.travis.yml

**delete**: cypress recording key from travis.yml
I've generated fresh new key in Cypress and it's saved as TravisCI environment variable now (this should/could have been a part of #451)

Remove cypress recording key from travis.yml

---

cypress/integration/controlOperations.js

Leaves our db in an inconsistent state when it fails. Taking this out till we can run against an in-memory firebase db

The change password test changes passwords

---

src/modules/auth/containers/PrivateRoute.jsx

The change password form was being reset when it modifies the 'user' state. This was due to the PrivateRoute component for some reason causing the entire application to re-mount whenever the 'user' state changes.
Returning separate routes based on auth state, rather than returning a single route and switching on the inner component seems to fix this, but to be honest I'm not sure why.

Show confirmation message when changing password

---

cypress.json
cypress/config.js
cypress/integration/controlOperations.js
cypress/support/commands.js
src/modules/auth/containers/PrivateRoute.jsx

Fixing 3 issues:
- Reintroduced changePassword UI test with same password to avoid putting Db to faulty state
- reLogin sign-in click validates page transition by checking URL(pathname)
- conditional test for presence of appDrawer "hamburger" button to ensure navigation in UI works fine

Cypress test issues - signIn button click, changePassword test faulty DB state, appDrawer button not always visible

---

cypress/integration/boxesTests.js
cypress/integration/controlOperations.js
cypress/integration/productsTests.js
cypress/integration/signupOrganization.js
cypress/support/commands.js
src/components/DeleteButton.jsx
src/components/DeleteConfirmationDialog.jsx
src/components/SubmitButton.jsx
src/modules/auth/components/AppDrawerAuth.jsx
src/modules/auth/components/PasswordChangeForm.jsx
src/modules/auth/components/SignInForm.jsx
src/modules/boxes/components/AddBoxDone.jsx
src/modules/boxes/components/AddBoxForm.jsx
src/modules/layout/components/AppDrawer.jsx
src/modules/layout/components/AppFrame.jsx
src/modules/layout/pages/DashboardPage.jsx
src/modules/products/components/ProductDialog.jsx
src/modules/products/containers/ProductTable.jsx
src/modules/products/pages/ProductsPage.jsx
src/modules/signup/components/CreateOrganizationForm.jsx
src/modules/signup/components/SignUpForm.jsx
src/modules/signup/containers/InviteLink.jsx
src/modules/signup/pages/HomePage.jsx

Switch data-cy attributes to data-testid - this is what react-testing-library uses (which we're adopting in https://github.com/boxwise/boxwise/pull/494) as their attributes to identify elements, and I think it makes sense to align. 
Cypress mentions data-testid as a ‘standard’ attribute too (https://docs.cypress.io/guides/references/best-practices.html#article).
Also noticed some accidental typos in the selectors (though they still seemed to work?!) so have pulled these out into a helper.

Switch data-cy attributes to data-testid
