boxwise/boxwise

- src/components/BoxList.js
At some point we can add a link but that's difficult for now (see #92).
> Add empty text for boxes

- src/actions/profile.js
- src/components/AddBoxDialogContainer.js
- src/components/AddProductDialogContainer.js
- src/queries/organizations.js
This will be useful at some point in the future. Closes #86
> Add time created/user who created to various things

- src/components/AddBoxDialogContainer.js
This is caused by #79
Closes #98
> Fix signing in after already being signed in

- src/components/BoxList.js
- src/components/BoxListContainer.js
- src/components/ProductSelect.js
Looks a bit like this, for now:
After we've done the MVP we can update to look more like the wireframes in #20.
> Filter boxes by product

- src/components/AddBoxDialogContainer.js
- src/components/AddBoxDone.js
- src/components/BoxList.js
This is the easiest way of generating numbers of boxes.
Right now, the boxnumber is not unique. Double occurrences are possible.
Feel free to change how the boxnumber is displayed in BoxList.js and AddBoxDone.js
> Add random box number without validation

- src/components/CreateOrganizationFlow.js
- src/components/CreateOrganizationForm.js
- src/components/InviteLink.js
- src/utils.js
> Hide button on onboarding invite step while loading

- firestore.indexes.json
- src/components/AddBoxDialogContainer.js
- src/components/BoxList.js
- src/components/BoxListContainer.js
- src/components/ProductTableContainer.js
- src/queries/products.js
- Products ordered alphabetically
- Boxes ordered by human ID. We haven't built searching by ID yet, so this works as an interim solution!
Closes #94
> Order various things

- src/components/AddProductDialog.js
- src/vendor/formik-material-ui/TextField.js
> Add helper text to product name in add form

- .eslintrc
- firestore.rules
- src/__tests__/firestore.rules.test.js
There are a bunch of unfinished things here, which I will open separate issues for. But this makes everything reasonably secure.
Closes #11
> Complete security rules

- README.md
> Add docs for running database tests

- src/pages/CreateLabelsPage.css
- src/pages/CreateLabelsPage.js
@bfirsh i rebased this branch according to your instructions.
So now it should be ready for a pull request.
> Exit from barcodes page

- .gitignore
- README.md
- package.json
- utils/generate-env.js
- yarn.lock
Got a small time to help, and spotted this thing
A simpler setup makes more attractive to whoever wants to contribute :)
Any change just say 👍
> Small script to make the initial setup easier

- src/actions/auth.js
- src/auth.js
- src/components/AppDrawerAuth.js
- src/containers/components/AppDrawerAuth.js
Another stuff we need to fix is move the organisation, user and profile creation to `actions`, and then connect the components which use these features 👍
> [Sentry errors fixes] - Correction post refactor

- package.json
- yarn.lock
Fixed by https://github.com/green-arrow/react-firestore/pull/23
My branch is that pull request rebased on master, which has some
fixes we need.
> Fix products page re-rendering unnecessarily

- checkdeploy.js
This is irritating every time you switch branch, etc. Just notify with a message.
> Don't automatically install dependencies

- src/components/AddBoxForm.js
Added logic in AddBoxForm to check if there are any products available. 
If there are no products:
- changed the "Create" button to a "Cancel" button
- display message saying that products must be added before creating a box
- display button linking to products page
> Prevent box creation when there are no products available

- src/components/AppDrawerAuth.js
- src/components/CreateOrganizationFlow.js
- src/components/SignUpForm.js
- src/pages/JoinPage.js
As per [this issue](https://github.com/boxwise/boxwise/issues/125), names are now asked for when signing up. Names are also displayed when possible in the sidebar.
> added name to user profiles

- README.md
> Fix .env.local filename in readme

- package.json
- src/App.js
- src/components/AddBoxForm.js
- src/index.js
- src/pages/DashboardPage.js
- yarn.lock
#196 Adds support for react-intl and implements extracted text for the Dashboard.
Needs more work to the extract all the other i18nalizable text.
> Issue-196: Make app support i18n via react-intl

- src/App.js
- src/actions/auth.js
- src/components/ResetPasswordForm.js
- src/containers/components/ResetPasswordForm.js
- src/containers/pages/ResetPasswordPage.js
- src/pages/ResetPasswordPage.js
- src/pages/SignInPage.js
- src/reducers/user.js
> Added a "Password Reset" page (linked to from sign in page)

- src/components/AppDrawerAuth.js
- src/components/BoxList.js
- src/components/ButtonWithProgress.js
- src/components/InviteLink.js
- src/components/ProductTable.js
- src/components/Progress.js
- src/pages/JoinPage.js
- src/router/AuthedRoute.js
- src/utils.js
Rebased version of #225. I have tested this and it works fine, but git got itself in a tangle with the merge commit, so I needed to open a new PR.
Closes #106
> 106: replace CircularProgress with a custom boxwise Progress component

- src/pages/CreateLabelsPage.css
- src/pages/CreateLabelsPage.js
#238
The organization name field has now a maximum width, wrapping text on multiple lines... and a really really long name is cut off after three lines of text.
> Longer title on box label is properly wrapped.

- config-overrides.js
> Enabled sourcemaps for production

- src/components/AddBoxForm.js
> Fixed inputMode property

- README.md
- config-overrides.js
- package.json
- utils/generate-env.js
- yarn.lock
> Config generation now only needs the project ID

- src/actions/box.js
- src/components/AddBoxDialog.js
- src/components/AddBoxDone.js
- src/components/AddBoxForm.js
When creating the first boxes with IHA no product or category was shown in AddBoxDone.
> Category and product in add box done

- README.md
Follow-up of #239. I haven't tested this, but I'm pretty sure this
button just opens a modal with the config details and does nothing
else.
> Remove unnecessary step from readme

- src/commons/utils/test-util.js
- src/components/ResetPasswordForm.test.js
- src/components/SignInForm.test.js
- src/components/SignUpForm.test.js
- Added test cases for Sign In, Sign Up and Reset Password components
- Un-skipped and fixed existing tests, added cases for unhappy path
- Extracted some reused logic into utils/test-util
> Add component unit tests (#60)

- CONTRIBUTING.md
As discussed with @HaGuesto and @rubenspgcavalcante the other day, we should write down the principles that have guided our development and technology choice so far.
Feel free to challenge!
> Add development principles

- README.md
I didn't notice master was failing due to a deployment issue, so let's make it more obvious
> Add build status icon to readme

- utils/import-random-data.js
**add**: script to generate random boxes and products for specified user
> Script to generate test data for specified user

- package.json
Was upgraded from 0.14 as noted here: https://github.com/typicode/husky
Upgraded by running 
`./node_modules/.bin/husky-upgrade
`
> Update usage of husky, as noted in pre-commit warning

- src/pages/ProductsPage.js
Mainly as a learning exercise for me :)
> Refactor products page to use hooks

- src/components/ScrollToTop.js
Mainly as a learning exercise for me :)
> Rewrite ScrollToTop to use useEffect

- package.json
- src/components/AddBoxDone.js
- src/components/AddBoxForm.js
- src/components/AppFrame.js
- src/components/BoxList.js
- src/components/ConfirmDeleteAlert.js
- src/components/CreateOrganizationFlow.js
- src/components/CreateOrganizationForm.js
- src/components/DialogToolbar.js
- src/components/InviteLink.js
- src/components/NotFound.js
- src/components/PasswordChangeForm.js
- src/components/ProductDialog.js
- src/components/ResetPasswordForm.js
- src/components/SignInForm.js
- src/components/SignUpForm.js
- src/pages/CreateOrganizationPage.js
- src/pages/DashboardPage.js
- src/pages/FindBoxMockupPage.js
- src/pages/HomePage.js
- src/pages/JoinPage.js
- src/pages/MakeBoxMockupPage.js
- src/pages/MockupsPage.js
- src/pages/ResetPasswordPage.js
- src/pages/SignInPage.js
- src/pages/__snapshots__/CreateOrganizationPage.snapshot.test.js.snap
- src/theme.js
- yarn.lock
Following the instructions here: https://material-ui.com/style/typography/#migration-to-typography-v2
and fixing warnings for other variant usages.
> Upgrade to Material UI 3.9

- .travis.yml
- README.md
- package.json
- yarn.lock
**add**: codecov package
**add**: Travis runs tests in coverage mode and uploads coverage reports.
**add**: code coverage badge to README.md
> Setup code coverage

- src/components/FormErrorText.jsx
- src/modules/auth/components/PasswordChangeForm.jsx
- src/modules/auth/components/ResetPasswordForm.jsx
- src/modules/auth/components/SignInForm.jsx
- src/modules/boxes/components/AddBoxForm.jsx
- src/modules/products/components/ProductDialog.jsx
- src/modules/signup/components/CreateOrganizationForm.jsx
- src/modules/signup/components/SignUpForm.jsx
Closes #156, adding styling to form error messages
> Wrap the form error messages in a component

- package.json
- public/index.html
- src/App.jsx
- src/modules/layout/components.js
- src/modules/layout/containers/GoogleAnalytics.jsx
- yarn.lock
* Remove react-ga
* Include userId in our analytics
* Anonymize the IP address
> Update Google Analytics - include userId and anonymizeIP

- src/setupTests.js
This is caused by the ScrollToTop component
> Fix warning in tests about window.scrollTo not being implemented

- src/modules/auth/containers/AppDrawerAuth.jsx
- src/modules/products/components/ProductDialog.jsx
- src/modules/products/containers/AddProductDialog.jsx
- src/modules/products/containers/EditProductDialog.jsx
- src/modules/products/containers/ProductTable.jsx
The Redux docs say it's very rarely needed, and it's definitely not needed here.
> Remove usage of mergeProps

- .travis.yml
- package.json
- yarn.lock
Following best practices documentation here: https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server
> Wait for the web server to start before running cypress

- src/modules/boxes/actions.js
- src/modules/boxes/api.ts
- src/modules/boxes/components/AddBoxDialog.jsx
- src/modules/boxes/components/AddBoxDone.jsx
- src/modules/boxes/components/AddBoxForm.jsx
- src/modules/boxes/containers/AddBoxDialog.jsx
- src/modules/boxes/containers/AddBoxDone.jsx
- src/modules/boxes/reducer.ts
- src/redux/storeTypes.ts
Move addBox to API interface, and simplify the flow for box creation in preparation for this being non-dialog based
> Move addBox to api interface

- .travis.yml
- run-browser-tests.sh
- run-build.sh
Playing with travis once again (I maybe figured out how to get closer to our ideal build scenario).
**Not ready to merge, I just need PR to run travis builds**
> Travis build split in 3 stages
